### ISSUE TITLE
HEX FILE NOT FOUND

### ISSUE THREAD

**Issue by LumitoLuma** [Bitbloq/QSSWeb2Board#38] opened 2020-09-26 11:58 UTC
When I try to compile a proyect using QSSWeb2Board, it always gives me the error "HEX FILE NOT FOUND"

Here is the full console output:
```
============================================
  QSSWebToBoard version:  "3.5.0"
Cleaning temp dir:  "C:/QSSWeb2Board/tmp/"
Cert: www.web2board.es
======================================================
  SSL Web2Board Server listening on port 9867
  DO NOT CLOSE THIS WINDOW // NO CIERRES ESTA VENTANA
======================================================
No Need to set permissions
No Need to set permissions
No Need to set permissions
Client connected: "" "https://bitbloq.bq.com"
Success:  "get_version"
Versions file  "C:/QSSWeb2Board/res/arduino/libraries/versions.json"
Current (remote) bitbloqLibs version  "1.7.5"
Local bitbloqLibs version  "1.7.5"
Success:  "set_lib_version"
Verifying sketch...
Arduino Path:  "C:/QSSWeb2Board/res/arduino/" arduino
Build Path:  "C:/QSSWeb2Board/tmp/build/"
Verify OK
Failure:  "compile"
"HEX FILE NOT FOUND"
"HEX FILE NOT FOUND"
```

How can I solve this?

**Comment by avalero** [comment] 2020-09-29 13:15
Hello, can you provide us with the code you ar trying to compile (or even better, the public link to the bitbloq project)?
As well, could you tell us your Operating System version?
Thanks

**Comment by LumitoLuma** [comment] 2020-09-29 15:04
I think I've solved the problem by "updating" the integrated Arduino IDE to the latest version. However, it seemed to be a incompatibility in my computer, since the program works perfectly in a Virtual Machine.
I have a Windows 10 2004.

**Comment by avalero** [comment] 2020-09-29 16:34
Is it possible that you have both de Arduino IDE and the integrated IDE? It seems that if you install the Arduino IDE on Windows it breaks the integrated IDE. We are happy you managed to solve it!
Have you tried the new Bitbloq? beta.bitbloq.cc

**Comment by LumitoLuma** [comment] 2020-09-30 07:23
@avalero Yes, I have the Arduino IDE installed. But when I uninstalled it, the problem persisted.

**Comment by avalero** [comment] 2020-09-30 07:39
Yes, the problem is the IDE modifies the env variables of the operating system (unless it is installed as portable), and thus, the QSSWeb2Board IDE does not find any more the paths.

We have moved to a version in which there is no need of QSSWeb2Board. You can try it (experimental) activating on your personal settings the "In-Browser" compilation checkbox. Let us know if it works for you. (it can be slow the first time as it has to download the compiler "into the browser". Then it should be just fine.

**Comment by LumitoLuma** [comment] 2020-09-30 07:43
@avalero I have tried it and worked perfectly for most of the boards, but with the mBot, it gives me the following error:
```
BitbloqOrion.h: Not such file or directory
```

**Comment by avalero** [comment] 2020-09-30 07:45
Yes, you are right, we have not yet included the makeblock libraries. 
Thanks for the feedback, I close this issue.

If you need anything else feel free to open a new one.

**Closed** 2021-01-04 20:00 UTC
